#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.

"""Run-local marker that points a completion predicate at controller state."""

from __future__ import annotations

import json
import os
import shlex
import stat
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from forge_common import parse_timestamp, read_json, stable_hash, timestamp_text, write_json

MARKER_KIND = "repository-skill-forge-run-marker"
MARKER_SCHEMA_VERSION = 1
MARKER_FILENAME = "run-marker.json"
LAUNCHER_FILENAME = "completion-predicate"
DEFAULT_MARKER_DIR = "/tmp/copilot-skill-forge"
MARKER_DIR_ENV = "FORGE_MARKER_DIR"
MARKER_PATH_ENV = "FORGE_RUN_MARKER"
DEFAULT_MAX_AGE_SECONDS = 21600
ACTIVE_PHASE = "active"
TERMINAL_PHASE = "terminal"
PHASES = (ACTIVE_PHASE, TERMINAL_PHASE)
REQUIRED_FIELDS = ("runId", "repository", "runDir", "statePath")

LAUNCHER_TEMPLATE = """#!/bin/sh
# Generated by repository-skill-forge run-marker.py. Do not edit.
# Stable entry point for the Copilot coding agent completion guard.
FORGE_RUN_MARKER=${{FORGE_RUN_MARKER:-{marker}}}
PYTHONDONTWRITEBYTECODE=1
export FORGE_RUN_MARKER PYTHONDONTWRITEBYTECODE
exec {python} {predicate} "$@"
"""


class MarkerError(ValueError):
    """A run marker is unreadable, unsupported, or internally inconsistent."""


def absolute(path: str | os.PathLike[str]) -> Path:
    """Expand and normalize to an absolute path without resolving symlinks."""
    return Path(os.path.abspath(os.path.expanduser(str(path))))


def resolve_marker_dir(
    explicit: str | os.PathLike[str] | None = None,
    environ: dict[str, str] | None = None,
) -> Path:
    values = os.environ if environ is None else environ
    if explicit:
        return absolute(explicit)
    return absolute(values.get(MARKER_DIR_ENV) or DEFAULT_MARKER_DIR)


def resolve_marker_path(
    explicit: str | os.PathLike[str] | None = None,
    marker_dir: str | os.PathLike[str] | None = None,
    environ: dict[str, str] | None = None,
) -> Path:
    values = os.environ if environ is None else environ
    if explicit:
        return absolute(explicit)
    if marker_dir:
        return resolve_marker_dir(marker_dir, values) / MARKER_FILENAME
    from_environment = values.get(MARKER_PATH_ENV)
    if from_environment:
        return absolute(from_environment)
    return resolve_marker_dir(None, values) / MARKER_FILENAME


def assert_private_directory(directory: Path) -> Path:
    """Reject a marker directory another local user could have planted or can edit."""
    remedy = (
        f"; set {MARKER_DIR_ENV} or pass --marker-dir to use a private directory"
    )
    try:
        info = directory.lstat()
    except OSError as error:
        raise MarkerError(f"marker directory is unusable: {error}") from error
    if not stat.S_ISDIR(info.st_mode):
        raise MarkerError(
            f"marker directory is not a real directory: {directory}{remedy}"
        )
    owner = getattr(os, "geteuid", None)
    if owner is not None and info.st_uid != owner():
        raise MarkerError(
            f"marker directory is not owned by this user: {directory}{remedy}"
        )
    if info.st_mode & (stat.S_IWGRP | stat.S_IWOTH):
        raise MarkerError(
            f"marker directory is group or world writable: {directory}{remedy}"
        )
    return directory


def ensure_private_directory(directory: Path) -> Path:
    if not os.path.lexists(directory):
        directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    return assert_private_directory(directory)


def run_id_for(state: dict[str, Any]) -> str:
    scope = state.get("scope")
    if not isinstance(scope, dict):
        raise MarkerError("extraction state is missing scope")
    return stable_hash(
        {
            "repository": scope.get("repository"),
            "windowStart": scope.get("windowStart"),
            "windowEnd": scope.get("windowEnd"),
            "runDir": state.get("runDir"),
        },
        16,
    )


def optional_path(value: str | os.PathLike[str] | None) -> str | None:
    return str(absolute(value)) if value else None


def build_marker(
    *,
    state: dict[str, Any],
    state_path: str | os.PathLike[str],
    run_id: str | None = None,
    checkpoint_path: str | os.PathLike[str] | None = None,
    ledger_path: str | os.PathLike[str] | None = None,
    skill_dir: str | os.PathLike[str] | None = None,
    predicate_path: str | os.PathLike[str] | None = None,
    now: datetime | None = None,
) -> dict[str, Any]:
    scope = state.get("scope")
    if not isinstance(scope, dict):
        raise MarkerError("extraction state is missing scope")
    repository = scope.get("repository")
    run_dir = state.get("runDir")
    if not isinstance(repository, str) or not repository:
        raise MarkerError("extraction state is missing scope.repository")
    if not isinstance(run_dir, str) or not run_dir:
        raise MarkerError("extraction state is missing runDir")
    stamp = timestamp_text(now or datetime.now(timezone.utc))
    return {
        "kind": MARKER_KIND,
        "schemaVersion": MARKER_SCHEMA_VERSION,
        "runId": run_id or run_id_for(state),
        "repository": repository,
        "runDir": run_dir,
        "statePath": str(absolute(state_path)),
        "checkpointPath": optional_path(checkpoint_path),
        "ledgerPath": optional_path(ledger_path),
        "skillDir": optional_path(skill_dir),
        "predicatePath": optional_path(predicate_path),
        "phase": ACTIVE_PHASE,
        "revision": 0,
        "pid": os.getpid(),
        "createdAt": stamp,
        "updatedAt": stamp,
        "snapshot": None,
        "terminalSummary": None,
    }


def validate_marker(marker: Any) -> dict[str, Any]:
    if not isinstance(marker, dict):
        raise MarkerError("run marker must be a JSON object")
    if marker.get("kind") != MARKER_KIND:
        raise MarkerError(f"run marker kind must be {MARKER_KIND}")
    if marker.get("schemaVersion") != MARKER_SCHEMA_VERSION:
        raise MarkerError(
            f"unsupported run marker schemaVersion: {marker.get('schemaVersion')!r}"
        )
    for field in REQUIRED_FIELDS:
        value = marker.get(field)
        if not isinstance(value, str) or not value:
            raise MarkerError(f"run marker is missing {field}")
    if marker.get("phase") not in PHASES:
        raise MarkerError(f"unsupported run marker phase: {marker.get('phase')!r}")
    revision = marker.get("revision")
    if not isinstance(revision, int) or isinstance(revision, bool) or revision < 0:
        raise MarkerError("run marker revision must be a non-negative integer")
    return marker


def read_marker(path: str | os.PathLike[str]) -> dict[str, Any]:
    marker_path = Path(path)
    try:
        marker = read_json(marker_path)
    except FileNotFoundError:
        raise
    except (OSError, TypeError, ValueError, json.JSONDecodeError) as error:
        raise MarkerError(f"run marker is unreadable: {error}") from error
    return validate_marker(marker)


def write_marker(path: str | os.PathLike[str], marker: dict[str, Any]) -> Path:
    validate_marker(marker)
    marker_path = Path(path)
    ensure_private_directory(marker_path.parent)
    write_json(marker_path, marker)
    return marker_path


def advance_marker(
    marker: dict[str, Any],
    *,
    phase: str | None = None,
    snapshot: Any = None,
    terminal_summary: Any = None,
    checkpoint_path: str | os.PathLike[str] | None = None,
    ledger_path: str | os.PathLike[str] | None = None,
    now: datetime | None = None,
) -> dict[str, Any]:
    if phase is not None and phase not in PHASES:
        raise MarkerError(f"unsupported run marker phase: {phase!r}")
    updated = dict(marker)
    updated["revision"] = int(marker.get("revision", 0)) + 1
    updated["updatedAt"] = timestamp_text(now or datetime.now(timezone.utc))
    updated["pid"] = os.getpid()
    if phase is not None:
        updated["phase"] = phase
    if snapshot is not None:
        updated["snapshot"] = snapshot
    if terminal_summary is not None:
        updated["terminalSummary"] = terminal_summary
    if checkpoint_path is not None:
        updated["checkpointPath"] = optional_path(checkpoint_path)
    if ledger_path is not None:
        updated["ledgerPath"] = optional_path(ledger_path)
    return updated


def marker_age_seconds(
    marker: dict[str, Any],
    *,
    now: datetime | None = None,
) -> float | None:
    updated_at = marker.get("updatedAt")
    if not isinstance(updated_at, str) or not updated_at:
        return None
    try:
        recorded = parse_timestamp(updated_at)
    except ValueError:
        return None
    current = now or datetime.now(timezone.utc)
    return max(0.0, (current - recorded).total_seconds())


def marker_is_stale(
    marker: dict[str, Any],
    *,
    max_age_seconds: float = DEFAULT_MAX_AGE_SECONDS,
    now: datetime | None = None,
) -> bool:
    if max_age_seconds <= 0:
        return False
    age = marker_age_seconds(marker, now=now)
    return age is None or age > max_age_seconds


def render_launcher(
    *,
    marker_path: str | os.PathLike[str],
    predicate_path: str | os.PathLike[str],
    python_executable: str | os.PathLike[str],
) -> str:
    return LAUNCHER_TEMPLATE.format(
        marker=shlex.quote(str(marker_path)),
        python=shlex.quote(str(python_executable)),
        predicate=shlex.quote(str(predicate_path)),
    )


def install_launcher(
    *,
    launcher_path: str | os.PathLike[str],
    marker_path: str | os.PathLike[str],
    predicate_path: str | os.PathLike[str],
    python_executable: str | os.PathLike[str],
) -> Path:
    target = Path(launcher_path)
    ensure_private_directory(target.parent)
    content = render_launcher(
        marker_path=marker_path,
        predicate_path=predicate_path,
        python_executable=python_executable,
    )
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=target.parent,
        prefix=f".{target.name}.",
        delete=False,
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)
    temporary.chmod(0o700)
    os.replace(temporary, target)
    return target
